// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'firebase_options.dart';


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBs7AxfYWDu388UfN58X87XwbjLWBqaL8',
    appId: '1:273030084006:web:0b6bf05a2862fea1cb0b67',
    messagingSenderId: '273030084006',
    projectId: 'projet-gsb',
    authDomain: 'projet-gsb.firebaseapp.com',
    storageBucket: 'projet-gsb.firebasestorage.app',
    measurementId: 'G-57Y8R34STK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3c98cHf9d81WYtuQ8WMHo2Ze0C1jCkKo',
    appId: '1:273030084006:android:36a816fe541c5e7ecb0b67',
    messagingSenderId: '273030084006',
    projectId: 'projet-gsb',
    storageBucket: 'projet-gsb.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBs7AxfYWDu388UfN58X87XwbjLWBqaL8',
    appId: '1:273030084006:web:cac3be0fc572413acb0b67',
    messagingSenderId: '273030084006',
    projectId: 'projet-gsb',
    authDomain: 'projet-gsb.firebaseapp.com',
    storageBucket: 'projet-gsb.firebasestorage.app',
    measurementId: 'G-J2VEH8GJVR',
  );

}